export interface RootPaths {
  root: string;
  dashboardRoot: string;
  appsRoot: string;
  emailRoot: string;
  eventsRoot: string;
  socialRoot: string;
  supportDeskRoot: string;
  componentsRoot: string;
  pagesRoot: string;
  authRoot: string;
  authCardRoot: string;
  userRoot: string;
  pricingRoot: string;
  faqRoot: string;
  errorsRoot: string;
  miscRoot: string;
  formsRoot: string;
  basicFormsRoot: string;
  advanceFormsRoot: string;
  tableRoot: string;
  chartsRoot: string;
  echartsRoot: string;
  iconsRoot: string;
  mapsRoot: string;
  carouselRoot: string;
  navsAndTabsRoot: string;
  picturesRoot: string;
  videosRoot: string;
  utilitiesRoot: string;
  docRoot: string;
  layoutRoot: string;
  adminRoot: string;
  developerRoot: string;
  referenceRoot: string;
}

export const rootPaths: RootPaths = {
  root: '/',
  dashboardRoot: 'dashboard',
  appsRoot: 'app',
  emailRoot: 'email',
  eventsRoot: 'events',
  socialRoot: 'social',
  supportDeskRoot: 'support-desk',
  componentsRoot: 'components',
  pagesRoot: 'pages',
  authRoot: 'authentication',
  authCardRoot: 'card',
  userRoot: 'user',
  pricingRoot: 'pricing',
  faqRoot: 'faq',
  errorsRoot: 'errors',
  miscRoot: 'miscellaneous',
  formsRoot: 'forms',
  basicFormsRoot: 'basic',
  advanceFormsRoot: 'advance',
  tableRoot: 'tables',
  chartsRoot: 'charts',
  echartsRoot: 'echarts',
  iconsRoot: 'icons',
  mapsRoot: 'maps',
  carouselRoot: 'carousel',
  navsAndTabsRoot: 'navs-and-tabs',
  picturesRoot: 'pictures',
  videosRoot: 'videos',
  utilitiesRoot: 'utilities',
  docRoot: 'documentation',
  layoutRoot: 'layouts',
  adminRoot: 'admin',
  developerRoot: 'developer',
  referenceRoot: 'reference'
};

export interface AppPaths {
  changelog: string;
  migration: string;
  widgets: string;
  landing: string;
  starter: string;
  error401: string;
  error404: string;
  error500: string;
  login: string;
  cardEveLogin: string;
  analytics: string;
  crm: string;
  saas: string;
  projectManagement: string;
  supportDesk: string;
  calendar: string;
  chat: string;
  kanban: string;
  emailDetail: string;
  emailInbox: string;
  emailCompose: string;
  eventDetail: string;
  createEvent: string;
  eventList: string;
  feed: string;
  activityLog: string;
  notifications: string;
  followers: string;
  ticketsCard: string;
  ticketsTable: string;
  contacts: string;
  contactDetails: string;
  ticketsPreview: string;
  quickLinks: string;
  reports: string;
  userProfile: string;
  userSettings: string;
  pricingDefault: string;
  pricingAlt: string;
  faqAlt: string;
  faqBasic: string;
  faqAccordion: string;
  associations: string;
  invitePeople: string;
  privacyPolicy: string;
  authTest: string;
  authStateTest: string;
  roleNavigationTester: string;
  userManagement: string;
  adminUserProfile: string;
  deadlineReports: string;
  operatorProfile: string;
  fleetVehicles: string;
  fleetVehicleProfile: string;
  fleetCranes: string;
  fleetCraneProfile: string;
  fleetTachographs: string;
  fleetTachographProfile: string;
  verticalNavLayout: string;
  topNavLayout: string;
  doubleTopNavLayout: string;
  comboNavLayout: string;
  formControl: string;
  inputGroup: string;
  select: string;
  checks: string;
  range: string;
  formLayout: string;
  advanceSelect: string;
  datePicker: string;
  editor: string;
  emojiButton: string;
  fileUploader: string;
  inputMask: string;
  rangeSlider: string;
  rating: string;
  floatingLabels: string;
  wizard: string;
  validation: string;
  basicTables: string;
  advanceTables: string;
  chartjs: string;
  d3js: string;
  echartsHowToUse: string;
  lineCharts: string;
  barCharts: string;
  candlestickCharts: string;
  geoMap: string;
  scatterCharts: string;
  pieCharts: string;
  radarCharts: string;
  heatmapCharts: string;
  fontAwesome: string;
  reactIcons: string;
  googleMap: string;
  leafletMap: string;
  alerts: string;
  accordion: string;
  animatedIcons: string;
  background: string;
  badges: string;
  breadcrumbs: string;
  buttons: string;
  calendarExample: string;
  cards: string;
  bootstrapCarousel: string;
  slickCarousel: string;
  collapse: string;
  cookieNotice: string;
  countup: string;
  dropdowns: string;
  draggable: string;
  listGroup: string;
  modals: string;
  offcanvas: string;
  navs: string;
  tabs: string;
  navbar: string;
  verticalNavbar: string;
  topNavbar: string;
  comboNavbar: string;
  doubleTopNavbar: string;
  avatar: string;
  images: string;
  figures: string;
  hoverbox: string;
  lightbox: string;
  progressBar: string;
  pagination: string;
  placeholder: string;
  popovers: string;
  scrollspy: string;
  search: string;
  spinners: string;
  timeline: string;
  toasts: string;
  tooltips: string;
  treeview: string;
  typedText: string;
  embedVideo: string;
  reactPlayer: string;
  borders: string;
  colors: string;
  backgroundColor: string;
  coloredLinks: string;
  display: string;
  visibility: string;
  stretchedLink: string;
  float: string;
  position: string;
  spacing: string;
  sizing: string;
  textTruncation: string;
  typography: string;
  verticalAlign: string;
  flex: string;
  grid: string;
  scrollBar: string;
  gettingStarted: string;
  configuration: string;
  styling: string;
  darkMode: string;
  plugin: string;
  faq: string;
  designFile: string;
  // Developer-only routes
  systemDebug: string;
  apiExplorer: string;
  databaseAdmin: string;
  logViewer: string;
  featureFlags: string;

  // Reference routes (developer-only)
  refDashboards: string;
  refComponents: string;
  refCharts: string;
  refUtilities: string;
  refDocumentation: string;
  refTest: string;
}

const paths: AppPaths = {
  changelog: '/changelog',
  migration: '/migration',
  widgets: '/widgets',
  landing: '/landing',
  starter: `/${rootPaths.pagesRoot}/starter`,
  error401: `/${rootPaths.errorsRoot}/401`,
  error404: `/${rootPaths.errorsRoot}/404`,
  error500: `/${rootPaths.errorsRoot}/500`,
  login: '/login',
  cardEveLogin: `/${rootPaths.authRoot}/${rootPaths.authCardRoot}/eve-login`,
  analytics: `/${rootPaths.dashboardRoot}/analytics`,
  crm: `/${rootPaths.dashboardRoot}/crm`,
  saas: `/${rootPaths.dashboardRoot}/saas`,
  projectManagement: `/${rootPaths.dashboardRoot}/project-management`,
  supportDesk: `/${rootPaths.dashboardRoot}/support-desk`,
  calendar: `/${rootPaths.appsRoot}/calendar`,
  chat: `/${rootPaths.appsRoot}/chat`,
  kanban: `/${rootPaths.appsRoot}/kanban`,
  emailDetail: `/${rootPaths.emailRoot}/email-detail`,
  emailInbox: `/${rootPaths.emailRoot}/inbox`,
  emailCompose: `/${rootPaths.emailRoot}/compose`,
  eventDetail: `/${rootPaths.eventsRoot}/event-detail`,
  createEvent: `/${rootPaths.eventsRoot}/create-an-event`,
  eventList: `/${rootPaths.eventsRoot}/event-list`,
  feed: `/${rootPaths.socialRoot}/feed`,
  activityLog: `/${rootPaths.socialRoot}/activity-log`,
  notifications: `/${rootPaths.socialRoot}/notifications`,
  followers: `/${rootPaths.socialRoot}/followers`,
  ticketsCard: `/${rootPaths.supportDeskRoot}/card-view`,
  ticketsTable: `/${rootPaths.supportDeskRoot}/table-view`,
  contacts: `/${rootPaths.supportDeskRoot}/contacts`,
  contactDetails: `/${rootPaths.supportDeskRoot}/contact-details`,
  ticketsPreview: `/${rootPaths.supportDeskRoot}/tickets-preview`,
  quickLinks: `/${rootPaths.supportDeskRoot}/quick-links`,
  reports: `/${rootPaths.supportDeskRoot}/reports`,
  userProfile: `/${rootPaths.userRoot}/profile`,
  userSettings: `/${rootPaths.userRoot}/settings`,
  pricingDefault: `/${rootPaths.pricingRoot}/pricing-default`,
  pricingAlt: `/${rootPaths.pricingRoot}/pricing-alt`,
  faqAlt: `/${rootPaths.faqRoot}/faq-alt`,
  faqBasic: `/${rootPaths.faqRoot}/faq-basic`,
  faqAccordion: `/${rootPaths.faqRoot}/faq-accordion`,
  associations: `/${rootPaths.miscRoot}/associations`,
  invitePeople: `/${rootPaths.miscRoot}/invite-people`,
  privacyPolicy: `/${rootPaths.miscRoot}/privacy-policy`,
  authTest: `/${rootPaths.miscRoot}/auth-test`,
  authStateTest: `/${rootPaths.miscRoot}/auth-state-test`,
  roleNavigationTester: '/test/role-navigation',
  userManagement: `/${rootPaths.adminRoot}/users`,
  adminUserProfile: `/${rootPaths.adminRoot}/user/profile/:userId`,
  deadlineReports: `/${rootPaths.adminRoot}/reports/deadlines`,
  operatorProfile: `/${rootPaths.adminRoot}/operator/profile/:operatorId`,
  fleetVehicles: '/fleet/vehicles',
  fleetVehicleProfile: '/fleet/vehicle/:vehicleId',
  fleetCranes: '/fleet/cranes',
  fleetCraneProfile: '/fleet/crane/:craneId',
  fleetTachographs: '/fleet/tachographs',
  fleetTachographProfile: '/fleet/tachograph/:tachographId',
  verticalNavLayout: `/${rootPaths.layoutRoot}/vertical-nav-layout`,
  topNavLayout: `/${rootPaths.layoutRoot}/top-nav-layout`,
  doubleTopNavLayout: `/${rootPaths.layoutRoot}/double-top-nav-layout`,
  comboNavLayout: `/${rootPaths.layoutRoot}/combo-nav-layout`,
  formControl: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/form-control`,
  inputGroup: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/input-group`,
  select: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/select`,
  checks: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/checks`,
  range: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/range`,
  formLayout: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/layout`,
  advanceSelect: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/advance-select`,
  datePicker: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/date-picker`,
  editor: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/editor`,
  emojiButton: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/emoji-button`,
  fileUploader: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/file-uploader`,
  inputMask: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/input-mask`,
  rangeSlider: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/range-slider`,
  rating: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/rating`,
  floatingLabels: `/${rootPaths.formsRoot}/floating-labels`,
  wizard: `/${rootPaths.formsRoot}/wizard`,
  validation: `/${rootPaths.formsRoot}/validation`,
  basicTables: `/${rootPaths.tableRoot}/basic-tables`,
  advanceTables: `/${rootPaths.tableRoot}/advance-tables`,
  chartjs: `/${rootPaths.chartsRoot}/chartjs`,
  d3js: `/${rootPaths.chartsRoot}/d3js`,
  echartsHowToUse: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/how-to-use`,
  lineCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/line-charts`,
  barCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/bar-charts`,
  candlestickCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/candlestick-charts`,
  geoMap: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/geo-map`,
  scatterCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/scatter-charts`,
  pieCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/pie-charts`,
  radarCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/radar-charts`,
  heatmapCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/heatmap-charts`,
  fontAwesome: `/${rootPaths.iconsRoot}/font-awesome`,
  reactIcons: `/${rootPaths.iconsRoot}/react-icons`,
  googleMap: `/${rootPaths.mapsRoot}/google-map`,
  leafletMap: `/${rootPaths.mapsRoot}/leaflet-map`,
  alerts: `/${rootPaths.componentsRoot}/alerts`,
  accordion: `/${rootPaths.componentsRoot}/accordion`,
  animatedIcons: `/${rootPaths.componentsRoot}/animated-icons`,
  background: `/${rootPaths.componentsRoot}/background`,
  badges: `/${rootPaths.componentsRoot}/badges`,
  breadcrumbs: `/${rootPaths.componentsRoot}/breadcrumb`,
  buttons: `/${rootPaths.componentsRoot}/buttons`,
  calendarExample: `/${rootPaths.componentsRoot}/calendar`,
  cards: `/${rootPaths.componentsRoot}/cards`,
  bootstrapCarousel: `/${rootPaths.componentsRoot}/${rootPaths.carouselRoot}/bootstrap`,
  slickCarousel: `/${rootPaths.componentsRoot}/${rootPaths.carouselRoot}/slick`,
  collapse: `/${rootPaths.componentsRoot}/collapse`,
  cookieNotice: `/${rootPaths.componentsRoot}/cookie-notice`,
  countup: `/${rootPaths.componentsRoot}/countup`,
  dropdowns: `/${rootPaths.componentsRoot}/dropdowns`,
  draggable: `/${rootPaths.componentsRoot}/draggable`,
  listGroup: `/${rootPaths.componentsRoot}/list-group`,
  modals: `/${rootPaths.componentsRoot}/modals`,
  offcanvas: `/${rootPaths.componentsRoot}/offcanvas`,
  navs: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/navs`,
  tabs: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/tabs`,
  navbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/navbar`,
  verticalNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/vertical-navbar`,
  topNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/top-navbar`,
  comboNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/combo-navbar`,
  doubleTopNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/double-top-navbar`,
  avatar: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/avatar`,
  images: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/images`,
  figures: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/figures`,
  hoverbox: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/hoverbox`,
  lightbox: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/lightbox`,
  progressBar: `/${rootPaths.componentsRoot}/progress-bar`,
  pagination: `/${rootPaths.componentsRoot}/pagination`,
  placeholder: `/${rootPaths.componentsRoot}/placeholder`,
  popovers: `/${rootPaths.componentsRoot}/popovers`,
  scrollspy: `/${rootPaths.componentsRoot}/scrollspy`,
  search: `/${rootPaths.componentsRoot}/search`,
  spinners: `/${rootPaths.componentsRoot}/spinners`,
  timeline: `/${rootPaths.componentsRoot}/timeline`,
  toasts: `/${rootPaths.componentsRoot}/toasts`,
  tooltips: `/${rootPaths.componentsRoot}/tooltips`,
  treeview: `/${rootPaths.componentsRoot}/treeview`,
  typedText: `/${rootPaths.componentsRoot}/typed-text`,
  embedVideo: `/${rootPaths.componentsRoot}/${rootPaths.videosRoot}/embed`,
  reactPlayer: `/${rootPaths.componentsRoot}/${rootPaths.videosRoot}/react-player`,
  borders: `/${rootPaths.utilitiesRoot}/borders`,
  colors: `/${rootPaths.utilitiesRoot}/colors`,
  backgroundColor: `/${rootPaths.utilitiesRoot}/background`,
  coloredLinks: `/${rootPaths.utilitiesRoot}/colored-links`,
  display: `/${rootPaths.utilitiesRoot}/display`,
  visibility: `/${rootPaths.utilitiesRoot}/visibility`,
  stretchedLink: `/${rootPaths.utilitiesRoot}/stretched-link`,
  float: `/${rootPaths.utilitiesRoot}/float`,
  position: `/${rootPaths.utilitiesRoot}/position`,
  spacing: `/${rootPaths.utilitiesRoot}/spacing`,
  sizing: `/${rootPaths.utilitiesRoot}/sizing`,
  textTruncation: `/${rootPaths.utilitiesRoot}/text-truncation`,
  typography: `/${rootPaths.utilitiesRoot}/typography`,
  verticalAlign: `/${rootPaths.utilitiesRoot}/vertical-align`,
  flex: `/${rootPaths.utilitiesRoot}/flex`,
  grid: `/${rootPaths.utilitiesRoot}/grid`,
  scrollBar: `/${rootPaths.utilitiesRoot}/scroll-bar`,
  gettingStarted: `/${rootPaths.docRoot}/getting-started`,
  configuration: `/${rootPaths.docRoot}/configuration`,
  styling: `/${rootPaths.docRoot}/styling`,
  darkMode: `/${rootPaths.docRoot}/dark-mode`,
  plugin: `/${rootPaths.docRoot}/plugin`,
  faq: `/${rootPaths.docRoot}/faq`,
  designFile: `/${rootPaths.docRoot}/design-file`,

  // Developer-only routes
  systemDebug: `/${rootPaths.developerRoot}/system-debug`,
  apiExplorer: `/${rootPaths.developerRoot}/api-explorer`,
  databaseAdmin: `/${rootPaths.developerRoot}/database-admin`,
  logViewer: `/${rootPaths.developerRoot}/log-viewer`,
  featureFlags: `/${rootPaths.developerRoot}/feature-flags`,

  // Reference routes (developer-only)
  refDashboards: `/${rootPaths.referenceRoot}/dashboards`,
  refComponents: `/${rootPaths.referenceRoot}/components`,
  refCharts: `/${rootPaths.referenceRoot}/charts`,
  refUtilities: `/${rootPaths.referenceRoot}/utilities`,
  refDocumentation: `/${rootPaths.referenceRoot}/documentation`,
  refTest: `/${rootPaths.referenceRoot}/test`
};

export default paths;
