package models

import "time"

// SubscriptionInvoice is an internal invoice generated by the renewal job
// per billing cycle. This is distinct from the billing module's FatturaPA
// invoices — those carry fiscal compliance weight, these are internal
// receipts that drive the charge flow.
type SubscriptionInvoice struct {
	UUID                  string        `bson:"uuid" json:"uuid"`
	Number                string        `bson:"number" json:"number"`
	SubscriptionUUID      string        `bson:"subscriptionUUID" json:"subscriptionUUID"`
	TenantUUID            string        `bson:"tenantUUID" json:"tenantUUID"`
	ServiceUUID           string        `bson:"serviceUUID" json:"serviceUUID"`
	PeriodStart           time.Time     `bson:"periodStart" json:"periodStart"`
	PeriodEnd             time.Time     `bson:"periodEnd" json:"periodEnd"`
	IssuedAt              time.Time     `bson:"issuedAt" json:"issuedAt"`
	DueAt                 time.Time     `bson:"dueAt" json:"dueAt"`
	SubtotalCents         int64         `bson:"subtotalCents" json:"subtotalCents"`
	VATCents              int64         `bson:"vatCents" json:"vatCents"`
	TotalCents            int64         `bson:"totalCents" json:"totalCents"`
	Currency              string        `bson:"currency" json:"currency"`
	Status                InvoiceStatus `bson:"status" json:"status"`
	StripePaymentIntentID string        `bson:"stripePaymentIntentID,omitempty" json:"stripePaymentIntentID,omitempty"`
	StripeRefundID        string        `bson:"stripeRefundID,omitempty" json:"stripeRefundID,omitempty"`
	PaidAt                *time.Time    `bson:"paidAt,omitempty" json:"paidAt,omitempty"`
	FailedAt              *time.Time    `bson:"failedAt,omitempty" json:"failedAt,omitempty"`
	RefundedAt            *time.Time    `bson:"refundedAt,omitempty" json:"refundedAt,omitempty"`
	FailureCode           string        `bson:"failureCode,omitempty" json:"failureCode,omitempty"`
	FailureMsg            string        `bson:"failureMsg,omitempty" json:"failureMsg,omitempty"`
	CreatedAt             time.Time     `bson:"createdAt" json:"createdAt"`
	UpdatedAt             time.Time     `bson:"updatedAt" json:"updatedAt"`
}
