export interface RootPaths {
  root: string;
  dashboardRoot: string;
  appsRoot: string;
  emailRoot: string;
  eventsRoot: string;
  socialRoot: string;
  supportDeskRoot: string;
  componentsRoot: string;
  pagesRoot: string;
  authRoot: string;
  authCardRoot: string;
  userRoot: string;
  pricingRoot: string;
  faqRoot: string;
  errorsRoot: string;
  miscRoot: string;
  formsRoot: string;
  basicFormsRoot: string;
  advanceFormsRoot: string;
  tableRoot: string;
  chartsRoot: string;
  echartsRoot: string;
  iconsRoot: string;
  mapsRoot: string;
  carouselRoot: string;
  navsAndTabsRoot: string;
  picturesRoot: string;
  videosRoot: string;
  utilitiesRoot: string;
  docRoot: string;
  layoutRoot: string;
  adminRoot: string;
  developerRoot: string;
  referenceRoot: string;
}

export const rootPaths: RootPaths = {
  root: '/',
  dashboardRoot: 'dashboard',
  appsRoot: 'app',
  emailRoot: 'email',
  eventsRoot: 'events',
  socialRoot: 'social',
  supportDeskRoot: 'support-desk',
  componentsRoot: 'components',
  pagesRoot: 'pages',
  authRoot: 'authentication',
  authCardRoot: 'card',
  userRoot: 'user',
  pricingRoot: 'pricing',
  faqRoot: 'faq',
  errorsRoot: 'errors',
  miscRoot: 'miscellaneous',
  formsRoot: 'forms',
  basicFormsRoot: 'basic',
  advanceFormsRoot: 'advance',
  tableRoot: 'tables',
  chartsRoot: 'charts',
  echartsRoot: 'echarts',
  iconsRoot: 'icons',
  mapsRoot: 'maps',
  carouselRoot: 'carousel',
  navsAndTabsRoot: 'navs-and-tabs',
  picturesRoot: 'pictures',
  videosRoot: 'videos',
  utilitiesRoot: 'utilities',
  docRoot: 'documentation',
  layoutRoot: 'layouts',
  adminRoot: 'admin',
  developerRoot: 'developer',
  referenceRoot: 'reference'
};

export interface AppPaths {
  changelog: string;
  migration: string;
  widgets: string;
  landing: string;
  starter: string;
  error401: string;
  error404: string;
  error500: string;
  login: string;
  cardEveLogin: string;
  analytics: string;
  crm: string;
  saas: string;
  projectManagement: string;
  supportDesk: string;
  calendar: string;
  chat: string;
  kanban: string;
  emailDetail: string;
  emailInbox: string;
  emailCompose: string;
  eventDetail: string;
  createEvent: string;
  eventList: string;
  feed: string;
  activityLog: string;
  notifications: string;
  followers: string;
  ticketsCard: string;
  ticketsTable: string;
  contacts: string;
  contactDetails: string;
  ticketsPreview: string;
  quickLinks: string;
  reports: string;
  userProfile: string;
  userSettings: string;
  userSecurity: string;
  pricingDefault: string;
  pricingAlt: string;
  faqAlt: string;
  faqBasic: string;
  faqAccordion: string;
  associations: string;
  invitePeople: string;
  privacyPolicy: string;
  authStateTest: string;
  userManagement: string;
  moduleManagement: string;
  roleManagement: string;
  tenantManagement: string;
  adminUserProfile: string;

  operatorProfile: string;
  documentTemplates: string;
  verticalNavLayout: string;
  topNavLayout: string;
  doubleTopNavLayout: string;
  comboNavLayout: string;
  formControl: string;
  inputGroup: string;
  select: string;
  checks: string;
  range: string;
  formLayout: string;
  advanceSelect: string;
  datePicker: string;
  editor: string;
  emojiButton: string;
  fileUploader: string;
  inputMask: string;
  rangeSlider: string;
  rating: string;
  floatingLabels: string;
  wizard: string;
  validation: string;
  tables: string;
  echartsHowToUse: string;
  lineCharts: string;
  barCharts: string;
  candlestickCharts: string;
  geoMap: string;
  scatterCharts: string;
  pieCharts: string;
  radarCharts: string;
  heatmapCharts: string;
  fontAwesome: string;
  reactIcons: string;
  googleMap: string;
  leafletMap: string;
  alerts: string;
  accordion: string;
  animatedIcons: string;
  background: string;
  badges: string;
  breadcrumbs: string;
  buttons: string;
  calendarExample: string;
  cards: string;
  bootstrapCarousel: string;
  slickCarousel: string;
  collapse: string;
  cookieNotice: string;
  countup: string;
  dropdowns: string;
  draggable: string;
  listGroup: string;
  modals: string;
  offcanvas: string;
  navs: string;
  tabs: string;
  navbar: string;
  verticalNavbar: string;
  topNavbar: string;
  comboNavbar: string;
  doubleTopNavbar: string;
  avatar: string;
  images: string;
  figures: string;
  hoverbox: string;
  lightbox: string;
  progressBar: string;
  pagination: string;
  placeholder: string;
  popovers: string;
  scrollspy: string;
  search: string;
  spinners: string;
  timeline: string;
  toasts: string;
  tooltips: string;
  treeview: string;
  typedText: string;
  embedVideo: string;
  reactPlayer: string;
  borders: string;
  colors: string;
  backgroundColor: string;
  coloredLinks: string;
  display: string;
  visibility: string;
  stretchedLink: string;
  float: string;
  position: string;
  spacing: string;
  sizing: string;
  textTruncation: string;
  typography: string;
  verticalAlign: string;
  flex: string;
  grid: string;
  scrollBar: string;
  gettingStarted: string;
  configuration: string;
  styling: string;
  darkMode: string;
  plugin: string;
  faq: string;
  designFile: string;
  // Developer-only routes
  systemDebug: string;
  apiExplorer: string;
  databaseAdmin: string;
  logViewer: string;
  featureFlags: string;

  // Reference routes (developer-only)
  // Reference Dashboards
  refDashboardsDefault: string;
  refDashboardsAnalytics: string;
  refDashboardsCrm: string;
  refDashboardsSaas: string;
  refDashboardsProjectManagement: string;
  refDashboardsSupportDesk: string;
  // Reference App Examples
  refAppCalendar: string;
  refAppChat: string;
  refAppKanban: string;
  refAppEmailInbox: string;
  refAppEmailCompose: string;
  refAppEmailDetail: string;
  refAppEventsCreate: string;
  refAppEventsList: string;
  refAppEventsDetail: string;
  refAppSocialFeed: string;
  refAppSocialActivityLog: string;
  refAppSocialNotifications: string;
  refAppSocialFollowers: string;
  refAppSupportDeskTableView: string;
  refAppSupportDeskCardView: string;
  refAppSupportDeskContacts: string;
  refAppSupportDeskContactDetails: string;
  refAppSupportDeskTicketsPreview: string;
  refAppSupportDeskQuickLinks: string;
  refAppSupportDeskReports: string;
  // Reference Components - UI
  refComponentsAlerts: string;
  refComponentsAccordion: string;
  refComponentsAnimatedIcons: string;
  refComponentsBackgrounds: string;
  refComponentsBadges: string;
  refComponentsBreadcrumbs: string;
  refComponentsButtons: string;
  refComponentsCalendar: string;
  refComponentsCards: string;
  refComponentsCarouselBootstrap: string;
  refComponentsCarouselSlick: string;
  refComponentsCollapse: string;
  refComponentsCookieNotice: string;
  refComponentsCountup: string;
  refComponentsDraggable: string;
  refComponentsDropdowns: string;
  refComponentsListGroup: string;
  refComponentsModals: string;
  refComponentsOffcanvas: string;
  refComponentsNavs: string;
  refComponentsNavbar: string;
  refComponentsVerticalNavbar: string;
  refComponentsTopNavbar: string;
  refComponentsDoubleTopNavbar: string;
  refComponentsComboNavbar: string;
  refComponentsTabs: string;
  refComponentsAvatar: string;
  refComponentsImages: string;
  refComponentsFigures: string;
  refComponentsHoverbox: string;
  refComponentsLightbox: string;
  refComponentsProgressBar: string;
  refComponentsPagination: string;
  refComponentsPlaceholder: string;
  refComponentsPopovers: string;
  refComponentsScrollspy: string;
  refComponentsSearch: string;
  refComponentsSpinners: string;
  refComponentsTimeline: string;
  refComponentsToasts: string;
  refComponentsTooltips: string;
  refComponentsTreeview: string;
  refComponentsTypedText: string;
  refComponentsVideoEmbed: string;
  refComponentsVideoReactPlayer: string;
  // Reference Components - Forms
  refFormsFormControl: string;
  refFormsInputGroup: string;
  refFormsSelect: string;
  refFormsChecks: string;
  refFormsRange: string;
  refFormsLayout: string;
  refFormsAdvanceSelect: string;
  refFormsDatePicker: string;
  refFormsEditor: string;
  refFormsEmojiButton: string;
  refFormsFileUploader: string;
  refFormsInputMask: string;
  refFormsRangeSlider: string;
  refFormsRating: string;
  refFormsFloatingLabels: string;
  refFormsWizard: string;
  refFormsValidation: string;
  // Reference Components - Tables
  refTables: string;
  // Reference Components - Icons
  refIconsFontAwesome: string;
  refIconsReactIcons: string;
  // Reference Components - Maps
  refMapsGoogle: string;
  refMapsLeaflet: string;
  // Reference Components - Widgets
  refWidgets: string;
  // Reference Charts (echarts only)
  refChartsEchartsHowToUse: string;
  refChartsEchartsLine: string;
  refChartsEchartsBar: string;
  refChartsEchartsCandlestick: string;
  refChartsEchartsGeoMap: string;
  refChartsEchartsScatter: string;
  refChartsEchartsPie: string;
  refChartsEchartsRadar: string;
  refChartsEchartsHeatmap: string;
  // Reference Utilities
  refUtilitiesBackground: string;
  refUtilitiesBorders: string;
  refUtilitiesColors: string;
  refUtilitiesColoredLinks: string;
  refUtilitiesDisplay: string;
  refUtilitiesVisibility: string;
  refUtilitiesStretchedLink: string;
  refUtilitiesFloat: string;
  refUtilitiesPosition: string;
  refUtilitiesSpacing: string;
  refUtilitiesSizing: string;
  refUtilitiesTextTruncation: string;
  refUtilitiesTypography: string;
  refUtilitiesVerticalAlign: string;
  refUtilitiesFlex: string;
  refUtilitiesGrid: string;
  refUtilitiesScrollBar: string;
  // Reference Pages
  refPagesLanding: string;
  refPagesStarter: string;
  refPagesPricingDefault: string;
  refPagesPricingAlt: string;
  refPagesFaqBasic: string;
  refPagesFaqAlt: string;
  refPagesFaqAccordion: string;
  refPagesMiscAssociations: string;
  refPagesMiscInvitePeople: string;
  refPagesMiscPrivacyPolicy: string;
  refPagesLayoutVerticalNav: string;
  refPagesLayoutTopNav: string;
  refPagesLayoutDoubleTop: string;
  refPagesLayoutComboNav: string;
  // Reference Documentation
  refDocGettingStarted: string;
  refDocConfiguration: string;
  refDocStyling: string;
  refDocDarkMode: string;
  refDocPlugins: string;
  refDocFaq: string;
  refDocDesignFile: string;
  refDocChangelog: string;
  refDocMigration: string;
}

const paths: AppPaths = {
  changelog: '/changelog',
  migration: '/migration',
  widgets: '/widgets',
  landing: '/landing',
  starter: `/${rootPaths.pagesRoot}/starter`,
  error401: `/${rootPaths.errorsRoot}/401`,
  error404: `/${rootPaths.errorsRoot}/404`,
  error500: `/${rootPaths.errorsRoot}/500`,
  login: '/login',
  cardEveLogin: `/${rootPaths.authRoot}/${rootPaths.authCardRoot}/eve-login`,
  analytics: `/${rootPaths.dashboardRoot}/analytics`,
  crm: `/${rootPaths.dashboardRoot}/crm`,
  saas: `/${rootPaths.dashboardRoot}/saas`,
  projectManagement: `/${rootPaths.dashboardRoot}/project-management`,
  supportDesk: `/${rootPaths.dashboardRoot}/support-desk`,
  calendar: `/${rootPaths.appsRoot}/calendar`,
  chat: `/${rootPaths.appsRoot}/chat`,
  kanban: `/${rootPaths.appsRoot}/kanban`,
  emailDetail: `/${rootPaths.emailRoot}/email-detail`,
  emailInbox: `/${rootPaths.emailRoot}/inbox`,
  emailCompose: `/${rootPaths.emailRoot}/compose`,
  eventDetail: `/${rootPaths.eventsRoot}/event-detail`,
  createEvent: `/${rootPaths.eventsRoot}/create-an-event`,
  eventList: `/${rootPaths.eventsRoot}/event-list`,
  feed: `/${rootPaths.socialRoot}/feed`,
  activityLog: `/${rootPaths.socialRoot}/activity-log`,
  notifications: `/${rootPaths.socialRoot}/notifications`,
  followers: `/${rootPaths.socialRoot}/followers`,
  ticketsCard: `/${rootPaths.supportDeskRoot}/card-view`,
  ticketsTable: `/${rootPaths.supportDeskRoot}/table-view`,
  contacts: `/${rootPaths.supportDeskRoot}/contacts`,
  contactDetails: `/${rootPaths.supportDeskRoot}/contact-details`,
  ticketsPreview: `/${rootPaths.supportDeskRoot}/tickets-preview`,
  quickLinks: `/${rootPaths.supportDeskRoot}/quick-links`,
  reports: `/${rootPaths.supportDeskRoot}/reports`,
  userProfile: `/${rootPaths.userRoot}/profile`,
  userSettings: `/${rootPaths.userRoot}/settings`,
  userSecurity: `/${rootPaths.userRoot}/security`,
  pricingDefault: `/${rootPaths.pricingRoot}/pricing-default`,
  pricingAlt: `/${rootPaths.pricingRoot}/pricing-alt`,
  faqAlt: `/${rootPaths.faqRoot}/faq-alt`,
  faqBasic: `/${rootPaths.faqRoot}/faq-basic`,
  faqAccordion: `/${rootPaths.faqRoot}/faq-accordion`,
  associations: `/${rootPaths.miscRoot}/associations`,
  invitePeople: `/${rootPaths.miscRoot}/invite-people`,
  privacyPolicy: `/${rootPaths.miscRoot}/privacy-policy`,
  authStateTest: `/${rootPaths.miscRoot}/auth-state-test`,
  userManagement: `/${rootPaths.adminRoot}/users`,
  moduleManagement: `/${rootPaths.adminRoot}/modules`,
  roleManagement: `/${rootPaths.adminRoot}/roles`,
  tenantManagement: `/${rootPaths.adminRoot}/tenants`,
  adminUserProfile: `/${rootPaths.adminRoot}/user/profile/:userId`,

  operatorProfile: `/${rootPaths.adminRoot}/operator/profile/:operatorId`,
  documentTemplates: '/documents/templates',
  verticalNavLayout: `/${rootPaths.layoutRoot}/vertical-nav-layout`,
  topNavLayout: `/${rootPaths.layoutRoot}/top-nav-layout`,
  doubleTopNavLayout: `/${rootPaths.layoutRoot}/double-top-nav-layout`,
  comboNavLayout: `/${rootPaths.layoutRoot}/combo-nav-layout`,
  formControl: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/form-control`,
  inputGroup: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/input-group`,
  select: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/select`,
  checks: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/checks`,
  range: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/range`,
  formLayout: `/${rootPaths.formsRoot}/${rootPaths.basicFormsRoot}/layout`,
  advanceSelect: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/advance-select`,
  datePicker: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/date-picker`,
  editor: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/editor`,
  emojiButton: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/emoji-button`,
  fileUploader: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/file-uploader`,
  inputMask: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/input-mask`,
  rangeSlider: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/range-slider`,
  rating: `/${rootPaths.formsRoot}/${rootPaths.advanceFormsRoot}/rating`,
  floatingLabels: `/${rootPaths.formsRoot}/floating-labels`,
  wizard: `/${rootPaths.formsRoot}/wizard`,
  validation: `/${rootPaths.formsRoot}/validation`,
  tables: `/${rootPaths.tableRoot}`,
  echartsHowToUse: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/how-to-use`,
  lineCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/line-charts`,
  barCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/bar-charts`,
  candlestickCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/candlestick-charts`,
  geoMap: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/geo-map`,
  scatterCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/scatter-charts`,
  pieCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/pie-charts`,
  radarCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/radar-charts`,
  heatmapCharts: `/${rootPaths.chartsRoot}/${rootPaths.echartsRoot}/heatmap-charts`,
  fontAwesome: `/${rootPaths.iconsRoot}/font-awesome`,
  reactIcons: `/${rootPaths.iconsRoot}/react-icons`,
  googleMap: `/${rootPaths.mapsRoot}/google-map`,
  leafletMap: `/${rootPaths.mapsRoot}/leaflet-map`,
  alerts: `/${rootPaths.componentsRoot}/alerts`,
  accordion: `/${rootPaths.componentsRoot}/accordion`,
  animatedIcons: `/${rootPaths.componentsRoot}/animated-icons`,
  background: `/${rootPaths.componentsRoot}/background`,
  badges: `/${rootPaths.componentsRoot}/badges`,
  breadcrumbs: `/${rootPaths.componentsRoot}/breadcrumb`,
  buttons: `/${rootPaths.componentsRoot}/buttons`,
  calendarExample: `/${rootPaths.componentsRoot}/calendar`,
  cards: `/${rootPaths.componentsRoot}/cards`,
  bootstrapCarousel: `/${rootPaths.componentsRoot}/${rootPaths.carouselRoot}/bootstrap`,
  slickCarousel: `/${rootPaths.componentsRoot}/${rootPaths.carouselRoot}/slick`,
  collapse: `/${rootPaths.componentsRoot}/collapse`,
  cookieNotice: `/${rootPaths.componentsRoot}/cookie-notice`,
  countup: `/${rootPaths.componentsRoot}/countup`,
  dropdowns: `/${rootPaths.componentsRoot}/dropdowns`,
  draggable: `/${rootPaths.componentsRoot}/draggable`,
  listGroup: `/${rootPaths.componentsRoot}/list-group`,
  modals: `/${rootPaths.componentsRoot}/modals`,
  offcanvas: `/${rootPaths.componentsRoot}/offcanvas`,
  navs: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/navs`,
  tabs: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/tabs`,
  navbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/navbar`,
  verticalNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/vertical-navbar`,
  topNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/top-navbar`,
  comboNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/combo-navbar`,
  doubleTopNavbar: `/${rootPaths.componentsRoot}/${rootPaths.navsAndTabsRoot}/double-top-navbar`,
  avatar: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/avatar`,
  images: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/images`,
  figures: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/figures`,
  hoverbox: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/hoverbox`,
  lightbox: `/${rootPaths.componentsRoot}/${rootPaths.picturesRoot}/lightbox`,
  progressBar: `/${rootPaths.componentsRoot}/progress-bar`,
  pagination: `/${rootPaths.componentsRoot}/pagination`,
  placeholder: `/${rootPaths.componentsRoot}/placeholder`,
  popovers: `/${rootPaths.componentsRoot}/popovers`,
  scrollspy: `/${rootPaths.componentsRoot}/scrollspy`,
  search: `/${rootPaths.componentsRoot}/search`,
  spinners: `/${rootPaths.componentsRoot}/spinners`,
  timeline: `/${rootPaths.componentsRoot}/timeline`,
  toasts: `/${rootPaths.componentsRoot}/toasts`,
  tooltips: `/${rootPaths.componentsRoot}/tooltips`,
  treeview: `/${rootPaths.componentsRoot}/treeview`,
  typedText: `/${rootPaths.componentsRoot}/typed-text`,
  embedVideo: `/${rootPaths.componentsRoot}/${rootPaths.videosRoot}/embed`,
  reactPlayer: `/${rootPaths.componentsRoot}/${rootPaths.videosRoot}/react-player`,
  borders: `/${rootPaths.utilitiesRoot}/borders`,
  colors: `/${rootPaths.utilitiesRoot}/colors`,
  backgroundColor: `/${rootPaths.utilitiesRoot}/background`,
  coloredLinks: `/${rootPaths.utilitiesRoot}/colored-links`,
  display: `/${rootPaths.utilitiesRoot}/display`,
  visibility: `/${rootPaths.utilitiesRoot}/visibility`,
  stretchedLink: `/${rootPaths.utilitiesRoot}/stretched-link`,
  float: `/${rootPaths.utilitiesRoot}/float`,
  position: `/${rootPaths.utilitiesRoot}/position`,
  spacing: `/${rootPaths.utilitiesRoot}/spacing`,
  sizing: `/${rootPaths.utilitiesRoot}/sizing`,
  textTruncation: `/${rootPaths.utilitiesRoot}/text-truncation`,
  typography: `/${rootPaths.utilitiesRoot}/typography`,
  verticalAlign: `/${rootPaths.utilitiesRoot}/vertical-align`,
  flex: `/${rootPaths.utilitiesRoot}/flex`,
  grid: `/${rootPaths.utilitiesRoot}/grid`,
  scrollBar: `/${rootPaths.utilitiesRoot}/scroll-bar`,
  gettingStarted: `/${rootPaths.docRoot}/getting-started`,
  configuration: `/${rootPaths.docRoot}/configuration`,
  styling: `/${rootPaths.docRoot}/styling`,
  darkMode: `/${rootPaths.docRoot}/dark-mode`,
  plugin: `/${rootPaths.docRoot}/plugin`,
  faq: `/${rootPaths.docRoot}/faq`,
  designFile: `/${rootPaths.docRoot}/design-file`,

  // Developer-only routes
  systemDebug: `/${rootPaths.developerRoot}/system-debug`,
  apiExplorer: `/${rootPaths.developerRoot}/api-explorer`,
  databaseAdmin: `/${rootPaths.developerRoot}/database-admin`,
  logViewer: `/${rootPaths.developerRoot}/log-viewer`,
  featureFlags: `/${rootPaths.developerRoot}/feature-flags`,

  // Reference routes (developer-only)
  // Reference Dashboards
  refDashboardsDefault: `/${rootPaths.referenceRoot}/dashboards/default`,
  refDashboardsAnalytics: `/${rootPaths.referenceRoot}/dashboards/analytics`,
  refDashboardsCrm: `/${rootPaths.referenceRoot}/dashboards/crm`,
  refDashboardsSaas: `/${rootPaths.referenceRoot}/dashboards/saas`,
  refDashboardsProjectManagement: `/${rootPaths.referenceRoot}/dashboards/project-management`,
  refDashboardsSupportDesk: `/${rootPaths.referenceRoot}/dashboards/support-desk`,
  // Reference App Examples
  refAppCalendar: `/${rootPaths.referenceRoot}/app-examples/calendar`,
  refAppChat: `/${rootPaths.referenceRoot}/app-examples/chat`,
  refAppKanban: `/${rootPaths.referenceRoot}/app-examples/kanban`,
  refAppEmailInbox: `/${rootPaths.referenceRoot}/app-examples/email/inbox`,
  refAppEmailCompose: `/${rootPaths.referenceRoot}/app-examples/email/compose`,
  refAppEmailDetail: `/${rootPaths.referenceRoot}/app-examples/email/detail`,
  refAppEventsCreate: `/${rootPaths.referenceRoot}/app-examples/events/create`,
  refAppEventsList: `/${rootPaths.referenceRoot}/app-examples/events/list`,
  refAppEventsDetail: `/${rootPaths.referenceRoot}/app-examples/events/detail`,
  refAppSocialFeed: `/${rootPaths.referenceRoot}/app-examples/social/feed`,
  refAppSocialActivityLog: `/${rootPaths.referenceRoot}/app-examples/social/activity-log`,
  refAppSocialNotifications: `/${rootPaths.referenceRoot}/app-examples/social/notifications`,
  refAppSocialFollowers: `/${rootPaths.referenceRoot}/app-examples/social/followers`,
  refAppSupportDeskTableView: `/${rootPaths.referenceRoot}/app-examples/support-desk/table-view`,
  refAppSupportDeskCardView: `/${rootPaths.referenceRoot}/app-examples/support-desk/card-view`,
  refAppSupportDeskContacts: `/${rootPaths.referenceRoot}/app-examples/support-desk/contacts`,
  refAppSupportDeskContactDetails: `/${rootPaths.referenceRoot}/app-examples/support-desk/contact-details`,
  refAppSupportDeskTicketsPreview: `/${rootPaths.referenceRoot}/app-examples/support-desk/tickets-preview`,
  refAppSupportDeskQuickLinks: `/${rootPaths.referenceRoot}/app-examples/support-desk/quick-links`,
  refAppSupportDeskReports: `/${rootPaths.referenceRoot}/app-examples/support-desk/reports`,
  // Reference Components - UI
  refComponentsAlerts: `/${rootPaths.referenceRoot}/components/alerts`,
  refComponentsAccordion: `/${rootPaths.referenceRoot}/components/accordion`,
  refComponentsAnimatedIcons: `/${rootPaths.referenceRoot}/components/animated-icons`,
  refComponentsBackgrounds: `/${rootPaths.referenceRoot}/components/backgrounds`,
  refComponentsBadges: `/${rootPaths.referenceRoot}/components/badges`,
  refComponentsBreadcrumbs: `/${rootPaths.referenceRoot}/components/breadcrumbs`,
  refComponentsButtons: `/${rootPaths.referenceRoot}/components/buttons`,
  refComponentsCalendar: `/${rootPaths.referenceRoot}/components/calendar`,
  refComponentsCards: `/${rootPaths.referenceRoot}/components/cards`,
  refComponentsCarouselBootstrap: `/${rootPaths.referenceRoot}/components/carousel/bootstrap`,
  refComponentsCarouselSlick: `/${rootPaths.referenceRoot}/components/carousel/slick`,
  refComponentsCollapse: `/${rootPaths.referenceRoot}/components/collapse`,
  refComponentsCookieNotice: `/${rootPaths.referenceRoot}/components/cookie-notice`,
  refComponentsCountup: `/${rootPaths.referenceRoot}/components/countup`,
  refComponentsDraggable: `/${rootPaths.referenceRoot}/components/draggable`,
  refComponentsDropdowns: `/${rootPaths.referenceRoot}/components/dropdowns`,
  refComponentsListGroup: `/${rootPaths.referenceRoot}/components/list-group`,
  refComponentsModals: `/${rootPaths.referenceRoot}/components/modals`,
  refComponentsOffcanvas: `/${rootPaths.referenceRoot}/components/offcanvas`,
  refComponentsNavs: `/${rootPaths.referenceRoot}/components/navs-and-tabs/navs`,
  refComponentsNavbar: `/${rootPaths.referenceRoot}/components/navs-and-tabs/navbar`,
  refComponentsVerticalNavbar: `/${rootPaths.referenceRoot}/components/navs-and-tabs/vertical-navbar`,
  refComponentsTopNavbar: `/${rootPaths.referenceRoot}/components/navs-and-tabs/top-navbar`,
  refComponentsDoubleTopNavbar: `/${rootPaths.referenceRoot}/components/navs-and-tabs/double-top-navbar`,
  refComponentsComboNavbar: `/${rootPaths.referenceRoot}/components/navs-and-tabs/combo-navbar`,
  refComponentsTabs: `/${rootPaths.referenceRoot}/components/navs-and-tabs/tabs`,
  refComponentsAvatar: `/${rootPaths.referenceRoot}/components/pictures/avatar`,
  refComponentsImages: `/${rootPaths.referenceRoot}/components/pictures/images`,
  refComponentsFigures: `/${rootPaths.referenceRoot}/components/pictures/figures`,
  refComponentsHoverbox: `/${rootPaths.referenceRoot}/components/pictures/hoverbox`,
  refComponentsLightbox: `/${rootPaths.referenceRoot}/components/pictures/lightbox`,
  refComponentsProgressBar: `/${rootPaths.referenceRoot}/components/progress-bar`,
  refComponentsPagination: `/${rootPaths.referenceRoot}/components/pagination`,
  refComponentsPlaceholder: `/${rootPaths.referenceRoot}/components/placeholder`,
  refComponentsPopovers: `/${rootPaths.referenceRoot}/components/popovers`,
  refComponentsScrollspy: `/${rootPaths.referenceRoot}/components/scrollspy`,
  refComponentsSearch: `/${rootPaths.referenceRoot}/components/search`,
  refComponentsSpinners: `/${rootPaths.referenceRoot}/components/spinners`,
  refComponentsTimeline: `/${rootPaths.referenceRoot}/components/timeline`,
  refComponentsToasts: `/${rootPaths.referenceRoot}/components/toasts`,
  refComponentsTooltips: `/${rootPaths.referenceRoot}/components/tooltips`,
  refComponentsTreeview: `/${rootPaths.referenceRoot}/components/treeview`,
  refComponentsTypedText: `/${rootPaths.referenceRoot}/components/typed-text`,
  refComponentsVideoEmbed: `/${rootPaths.referenceRoot}/components/videos/embed`,
  refComponentsVideoReactPlayer: `/${rootPaths.referenceRoot}/components/videos/react-player`,
  // Reference Components - Forms
  refFormsFormControl: `/${rootPaths.referenceRoot}/forms/basic/form-control`,
  refFormsInputGroup: `/${rootPaths.referenceRoot}/forms/basic/input-group`,
  refFormsSelect: `/${rootPaths.referenceRoot}/forms/basic/select`,
  refFormsChecks: `/${rootPaths.referenceRoot}/forms/basic/checks`,
  refFormsRange: `/${rootPaths.referenceRoot}/forms/basic/range`,
  refFormsLayout: `/${rootPaths.referenceRoot}/forms/basic/layout`,
  refFormsAdvanceSelect: `/${rootPaths.referenceRoot}/forms/advance/advance-select`,
  refFormsDatePicker: `/${rootPaths.referenceRoot}/forms/advance/date-picker`,
  refFormsEditor: `/${rootPaths.referenceRoot}/forms/advance/editor`,
  refFormsEmojiButton: `/${rootPaths.referenceRoot}/forms/advance/emoji-button`,
  refFormsFileUploader: `/${rootPaths.referenceRoot}/forms/advance/file-uploader`,
  refFormsInputMask: `/${rootPaths.referenceRoot}/forms/advance/input-mask`,
  refFormsRangeSlider: `/${rootPaths.referenceRoot}/forms/advance/range-slider`,
  refFormsRating: `/${rootPaths.referenceRoot}/forms/advance/rating`,
  refFormsFloatingLabels: `/${rootPaths.referenceRoot}/forms/floating-labels`,
  refFormsWizard: `/${rootPaths.referenceRoot}/forms/wizard`,
  refFormsValidation: `/${rootPaths.referenceRoot}/forms/validation`,
  // Reference Components - Tables
  refTables: `/${rootPaths.referenceRoot}/tables`,
  // Reference Components - Icons
  refIconsFontAwesome: `/${rootPaths.referenceRoot}/icons/font-awesome`,
  refIconsReactIcons: `/${rootPaths.referenceRoot}/icons/react-icons`,
  // Reference Components - Maps
  refMapsGoogle: `/${rootPaths.referenceRoot}/maps/google`,
  refMapsLeaflet: `/${rootPaths.referenceRoot}/maps/leaflet`,
  // Reference Components - Widgets
  refWidgets: `/${rootPaths.referenceRoot}/widgets`,
  // Reference Charts (echarts only — chartjs and d3js were removed)
  refChartsEchartsHowToUse: `/${rootPaths.referenceRoot}/charts/echarts/how-to-use`,
  refChartsEchartsLine: `/${rootPaths.referenceRoot}/charts/echarts/line-charts`,
  refChartsEchartsBar: `/${rootPaths.referenceRoot}/charts/echarts/bar-charts`,
  refChartsEchartsCandlestick: `/${rootPaths.referenceRoot}/charts/echarts/candlestick-charts`,
  refChartsEchartsGeoMap: `/${rootPaths.referenceRoot}/charts/echarts/geo-map`,
  refChartsEchartsScatter: `/${rootPaths.referenceRoot}/charts/echarts/scatter-charts`,
  refChartsEchartsPie: `/${rootPaths.referenceRoot}/charts/echarts/pie-charts`,
  refChartsEchartsRadar: `/${rootPaths.referenceRoot}/charts/echarts/radar-charts`,
  refChartsEchartsHeatmap: `/${rootPaths.referenceRoot}/charts/echarts/heatmap-charts`,
  // Reference Utilities
  refUtilitiesBackground: `/${rootPaths.referenceRoot}/utilities/background`,
  refUtilitiesBorders: `/${rootPaths.referenceRoot}/utilities/borders`,
  refUtilitiesColors: `/${rootPaths.referenceRoot}/utilities/colors`,
  refUtilitiesColoredLinks: `/${rootPaths.referenceRoot}/utilities/colored-links`,
  refUtilitiesDisplay: `/${rootPaths.referenceRoot}/utilities/display`,
  refUtilitiesVisibility: `/${rootPaths.referenceRoot}/utilities/visibility`,
  refUtilitiesStretchedLink: `/${rootPaths.referenceRoot}/utilities/stretched-link`,
  refUtilitiesFloat: `/${rootPaths.referenceRoot}/utilities/float`,
  refUtilitiesPosition: `/${rootPaths.referenceRoot}/utilities/position`,
  refUtilitiesSpacing: `/${rootPaths.referenceRoot}/utilities/spacing`,
  refUtilitiesSizing: `/${rootPaths.referenceRoot}/utilities/sizing`,
  refUtilitiesTextTruncation: `/${rootPaths.referenceRoot}/utilities/text-truncation`,
  refUtilitiesTypography: `/${rootPaths.referenceRoot}/utilities/typography`,
  refUtilitiesVerticalAlign: `/${rootPaths.referenceRoot}/utilities/vertical-align`,
  refUtilitiesFlex: `/${rootPaths.referenceRoot}/utilities/flex`,
  refUtilitiesGrid: `/${rootPaths.referenceRoot}/utilities/grid`,
  refUtilitiesScrollBar: `/${rootPaths.referenceRoot}/utilities/scroll-bar`,
  // Reference Pages
  refPagesLanding: `/${rootPaths.referenceRoot}/pages/landing`,
  refPagesStarter: `/${rootPaths.referenceRoot}/pages/starter`,
  refPagesPricingDefault: `/${rootPaths.referenceRoot}/pages/pricing/default`,
  refPagesPricingAlt: `/${rootPaths.referenceRoot}/pages/pricing/alt`,
  refPagesFaqBasic: `/${rootPaths.referenceRoot}/pages/faq/basic`,
  refPagesFaqAlt: `/${rootPaths.referenceRoot}/pages/faq/alt`,
  refPagesFaqAccordion: `/${rootPaths.referenceRoot}/pages/faq/accordion`,
  refPagesMiscAssociations: `/${rootPaths.referenceRoot}/pages/miscellaneous/associations`,
  refPagesMiscInvitePeople: `/${rootPaths.referenceRoot}/pages/miscellaneous/invite-people`,
  refPagesMiscPrivacyPolicy: `/${rootPaths.referenceRoot}/pages/miscellaneous/privacy-policy`,
  refPagesLayoutVerticalNav: `/${rootPaths.referenceRoot}/pages/layouts/vertical-nav`,
  refPagesLayoutTopNav: `/${rootPaths.referenceRoot}/pages/layouts/top-nav`,
  refPagesLayoutDoubleTop: `/${rootPaths.referenceRoot}/pages/layouts/double-top`,
  refPagesLayoutComboNav: `/${rootPaths.referenceRoot}/pages/layouts/combo-nav`,
  // Reference Documentation
  refDocGettingStarted: `/${rootPaths.referenceRoot}/documentation/getting-started`,
  refDocConfiguration: `/${rootPaths.referenceRoot}/documentation/configuration`,
  refDocStyling: `/${rootPaths.referenceRoot}/documentation/styling`,
  refDocDarkMode: `/${rootPaths.referenceRoot}/documentation/dark-mode`,
  refDocPlugins: `/${rootPaths.referenceRoot}/documentation/plugins`,
  refDocFaq: `/${rootPaths.referenceRoot}/documentation/faq`,
  refDocDesignFile: `/${rootPaths.referenceRoot}/documentation/design-file`,
  refDocChangelog: `/${rootPaths.referenceRoot}/documentation/changelog`,
  refDocMigration: `/${rootPaths.referenceRoot}/documentation/migration`
};

export default paths;
