package models

// ActivityKind enumerates every event type the marketing addon stores
// in marketing_activities. The enum is static by design (Phase 2
// resolved decision): adding a new kind = patching this file. A
// runtime registry (other addons calling RegisterKind at boot) is
// possible but deferred until a concrete second-addon consumer asks
// for it.
//
// Schema reference:
// docs/plans/marketing-addon/schemas/marketing_activities.md §kind.
type ActivityKind string

const (
	// Email — populated by ESP webhook ingestion (Phase 5) and by
	// the engagement-export CSV import (Phase 3 extension).
	KindEmailSent         ActivityKind = "email_sent"
	KindEmailOpened       ActivityKind = "email_opened"
	KindEmailClicked      ActivityKind = "email_clicked"
	KindEmailBounced      ActivityKind = "email_bounced"
	KindEmailUnsubscribed ActivityKind = "email_unsubscribed"
	KindEmailComplained   ActivityKind = "email_complained"

	// Events — venue / webinar / conference attendance flows. Source
	// is typically the importer (engagement export) or a future
	// event-management integration.
	KindEventInvited    ActivityKind = "event_invited"
	KindEventRegistered ActivityKind = "event_registered"
	KindEventAttended   ActivityKind = "event_attended"
	KindEventNoShow     ActivityKind = "event_no_show"
	KindEventCancelled  ActivityKind = "event_cancelled"

	// Web / form — touchpoints generated by external integrations
	// (form embeds, content gates, page-view trackers).
	KindFormSubmitted     ActivityKind = "form_submitted"
	KindPageVisited       ActivityKind = "page_visited"
	KindContentDownloaded ActivityKind = "content_downloaded"

	// Direct — manual operator input from the contact-detail
	// "Add activity" affordance. Restricted to the ManualKinds slice
	// at the handler layer (you can't POST email_opened by hand).
	KindCallMade    ActivityKind = "call_made"
	KindMeetingHeld ActivityKind = "meeting_held"
	KindNoteAdded   ActivityKind = "note_added"

	// System — emitted by the addon itself (auto-emission listeners
	// in services/autoemit, Phase 4 card flows). KindCorrectedBy is
	// the append-only correction signal: a new activity pointing at
	// the erroneous one via refs.correctsActivityUuid; the engine
	// de-applies the corrected row.
	KindImported          ActivityKind = "imported"
	KindMerged            ActivityKind = "merged"
	KindTagAdded          ActivityKind = "tag_added"
	KindTagRemoved        ActivityKind = "tag_removed"
	KindCardIssued        ActivityKind = "card_issued"         // Phase 4 fills payload
	KindCardStatusChanged ActivityKind = "card_status_changed" // Phase 4 fills payload
	KindCorrectedBy       ActivityKind = "corrected_by"
)

// AllKinds lists every declared kind. Consumed by handler validation
// (rejecting unknown kinds on POST) and by the scoring engine when
// expanding a rule's "*" wildcard.
var AllKinds = []ActivityKind{
	KindEmailSent, KindEmailOpened, KindEmailClicked, KindEmailBounced,
	KindEmailUnsubscribed, KindEmailComplained,
	KindEventInvited, KindEventRegistered, KindEventAttended,
	KindEventNoShow, KindEventCancelled,
	KindFormSubmitted, KindPageVisited, KindContentDownloaded,
	KindCallMade, KindMeetingHeld, KindNoteAdded,
	KindImported, KindMerged, KindTagAdded, KindTagRemoved,
	KindCardIssued, KindCardStatusChanged, KindCorrectedBy,
}

// ManualKinds restricts the POST /v1/marketing/activities surface to
// the kinds an operator can legitimately type by hand. Email opens,
// page visits, etc. arrive via importers and webhooks — never as a
// manual entry, otherwise the dedup_key invariant breaks.
var ManualKinds = []ActivityKind{
	KindCallMade, KindMeetingHeld, KindNoteAdded, KindCorrectedBy,
}

// IsKnownKind reports whether k matches one of the declared
// ActivityKind constants. Used at handler boundaries to reject
// unrecognised payloads.
func IsKnownKind(k ActivityKind) bool {
	for _, known := range AllKinds {
		if known == k {
			return true
		}
	}
	return false
}

// IsManualKind reports whether the POST handler should accept k as a
// manually-entered activity.
func IsManualKind(k ActivityKind) bool {
	for _, m := range ManualKinds {
		if m == k {
			return true
		}
	}
	return false
}

// ActivitySource names the channel that produced an activity row.
// Recorded on every Activity for audit + filterability. Distinct
// from ProvenanceSource.Importer (which is per-record provenance,
// not per-event).
type ActivitySource string

const (
	ActivitySourceImporter       ActivitySource = "importer"
	ActivitySourceCampaignEngine ActivitySource = "campaign_engine"
	ActivitySourceWebhook        ActivitySource = "webhook"
	ActivitySourceManual         ActivitySource = "manual"
	ActivitySourceSystem         ActivitySource = "system"
)

// AllSources lists every declared ActivitySource value.
var AllSources = []ActivitySource{
	ActivitySourceImporter, ActivitySourceCampaignEngine,
	ActivitySourceWebhook, ActivitySourceManual, ActivitySourceSystem,
}

// IsKnownSource reports whether s matches one of the declared
// ActivitySource constants.
func IsKnownSource(s ActivitySource) bool {
	for _, known := range AllSources {
		if known == s {
			return true
		}
	}
	return false
}
