// Phase 6 dashboard — transactions list. Backend's MeListTransactions
// fans out across every owner the caller may act under (user + every
// owned tenant); the SPA narrows that fan-out via OwnerScopeSwitcher.
//
// Transactions are mostly auto-generated by the renewal job's off-session
// charges, so this view is read-only — refunds and disputes are admin-
// only on the Tier-1 console.
import { Link } from 'react-router-dom';
import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';

import { listMyTransactions, type Transaction } from '@/api/payments';
import { useMe } from '@/auth/useMe';
import { useOwnerScope, ownerQuery } from '@/auth/ownerScope';
import { OwnerScopeSwitcher } from '@/components/OwnerScopeSwitcher';
import { formatDate, formatPrice } from '@/lib/format';

export function TransactionsPage() {
  const { t, i18n } = useTranslation();
  const { data: me } = useMe();
  const { scope, setScope, ownedTenants, hasTenants } = useOwnerScope();
  const filter = useMemo(() => ownerQuery(scope, me?.id), [scope, me?.id]);
  const language = i18n.resolvedLanguage ?? 'it';

  const txs = useQuery({
    queryKey: ['me', 'transactions', filter],
    queryFn: ({ signal }) => listMyTransactions(filter, signal),
  });

  const items = useMemo(() => {
    const list = txs.data?.items ?? [];
    return [...list].sort(
      (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );
  }, [txs.data]);

  return (
    <section className="mx-auto max-w-5xl px-6 py-12">
      <header className="mb-8 flex flex-wrap items-end justify-between gap-4">
        <div>
          <Link to="/account" className="mb-2 inline-block text-sm text-slate-600 hover:underline">
            ← {t('account.back')}
          </Link>
          <h1 className="text-3xl font-semibold tracking-tight">
            {t('dashboard.transactions.title')}
          </h1>
          <p className="mt-1 text-slate-600">{t('dashboard.transactions.subtitle')}</p>
        </div>
        <OwnerScopeSwitcher
          scope={scope}
          setScope={setScope}
          ownedTenants={ownedTenants}
          hasTenants={hasTenants}
        />
      </header>

      {txs.isLoading && <p className="text-slate-500">{t('loading')}</p>}
      {txs.isError && (
        <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">
          {t('error.generic')}
        </p>
      )}

      {!txs.isLoading && items.length === 0 && (
        <p className="rounded-lg border border-dashed border-slate-300 bg-white p-10 text-center text-slate-600">
          {t('dashboard.transactions.empty')}
        </p>
      )}

      {items.length > 0 && (
        <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white shadow-sm">
          <table className="min-w-full divide-y divide-slate-200 text-sm">
            <thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500">
              <tr>
                <Th>{t('dashboard.transactions.date')}</Th>
                <Th>{t('dashboard.transactions.amount')}</Th>
                <Th>{t('dashboard.transactions.status')}</Th>
                <Th>{t('dashboard.transactions.provider')}</Th>
                <Th>{t('dashboard.transactions.reference')}</Th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {items.map((tx) => (
                <TxRow key={tx.uuid} tx={tx} language={language} />
              ))}
            </tbody>
          </table>
        </div>
      )}
    </section>
  );
}

function TxRow({ tx, language }: { tx: Transaction; language: string }) {
  const { t } = useTranslation();
  const date = tx.chargedAt ?? tx.createdAt;
  const amount = formatPrice(tx.amountCents, tx.currency, language);
  const refunded = tx.refundedCents
    ? formatPrice(tx.refundedCents, tx.currency, language)
    : null;

  return (
    <tr>
      <Td>{formatDate(date, language)}</Td>
      <Td>
        <span className="font-medium text-slate-900">{amount}</span>
        {refunded && (
          <span className="ml-2 text-xs text-slate-500">
            {t('dashboard.transactions.refundedAmount', { amount: refunded })}
          </span>
        )}
      </Td>
      <Td>
        <TxStatusBadge status={tx.status} />
        {tx.failureMsg && (
          <p className="mt-1 text-xs text-red-700">{tx.failureMsg}</p>
        )}
      </Td>
      <Td className="capitalize">{tx.provider}</Td>
      <Td className="font-mono text-xs text-slate-500">
        {tx.providerTxID || '—'}
      </Td>
    </tr>
  );
}

function TxStatusBadge({ status }: { status: Transaction['status'] }) {
  const { t } = useTranslation();
  const tone = TX_TONE[status] ?? 'bg-slate-100 text-slate-700';
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${tone}`}
    >
      {t(`dashboard.transactions.statusValue.${status}`, { defaultValue: status })}
    </span>
  );
}

const TX_TONE: Record<Transaction['status'], string> = {
  pending: 'bg-slate-100 text-slate-700',
  requires_action: 'bg-amber-50 text-amber-700',
  succeeded: 'bg-emerald-50 text-emerald-700',
  failed: 'bg-red-50 text-red-700',
  refunded: 'bg-slate-100 text-slate-500',
  partially_refunded: 'bg-slate-100 text-slate-500',
};

function Th({ children }: { children?: React.ReactNode }) {
  return <th className="px-4 py-3 text-left font-medium">{children}</th>;
}

function Td({
  children,
  className = '',
}: {
  children?: React.ReactNode;
  className?: string;
}) {
  return <td className={`px-4 py-3 align-top text-slate-700 ${className}`}>{children}</td>;
}
